# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/FH309/Desktop/eq2/eq2.cache/wt [current_project]
set_property parent.project_path C:/Users/FH309/Desktop/eq2/eq2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/FH309/Desktop/eq2/eq2.srcs/sources_1/new/Comparator.vhd
  C:/Users/FH309/Desktop/eq2/eq2.srcs/sources_1/new/eq2.vhd
  C:/Users/FH309/Desktop/eq2/eq2.srcs/sources_1/new/eq_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/FH309/Desktop/eq2/eq2.srcs/constrs_1/imports/hdl/Nexys4_DDR_chu.xdc
set_property used_in_implementation false [get_files C:/Users/FH309/Desktop/eq2/eq2.srcs/constrs_1/imports/hdl/Nexys4_DDR_chu.xdc]


synth_design -top eq_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef eq_top.dcp

catch { report_utilization -file eq_top_utilization_synth.rpt -pb eq_top_utilization_synth.pb }
