# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {7}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {8}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.cache/wt [current_project]
set_property parent.project_path C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/cpu.xci
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_2/bd_3914_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_2/bd_3914_ilmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_3/bd_3914_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_3/bd_3914_dlmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_4/bd_3914_dlmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_5/bd_3914_ilmb_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_6/bd_3914_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_7/bd_3914_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/ip/ip_7/bd_3914_iomodule_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/bd_0/bd_3914_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/cpu_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/cpu_ooc.xdc]
set_property is_locked true [get_files c:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/ip/cpu/cpu.xci]

read_vhdl -library xil_defaultlib {
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/fifo/reg_file.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/fifo/fifo_ctrl.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/uart/uart_tx.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/uart/uart_rx.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/uart/baud_gen.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/fifo/fifo.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/mcs_sys/chu_io_map.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/uart/uart.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/uart/chu_uart.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/timer/chu_timer.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/io_basic/chu_gpo.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/io_core/io_basic/chu_gpi.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/bridge/chu_mmio_controller.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/mcs_sys/mcs_sys_vanilla/mmio_sys_vanilla.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/bridge/chu_mcs_bridge.vhd
  C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/sources_1/imports/hdl/mcs_sys/mcs_sys_vanilla/mcs_top_vanilla.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/constrs_1/imports/hdl/Nexys4_DDR_chu.xdc
set_property used_in_implementation false [get_files C:/Users/FH309/Desktop/vanilla_fpro/vanilla_fpro.srcs/constrs_1/imports/hdl/Nexys4_DDR_chu.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mcs_top_vanilla -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mcs_top_vanilla.dcp

catch { report_utilization -file mcs_top_vanilla_utilization_synth.rpt -pb mcs_top_vanilla_utilization_synth.pb }
